config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'samples/:action', controller: 'samples'

  resources :clients
  resources :users do
    get :confirm, on: :member
    get :invite, on: :member
    get :login_as, on: :member
  end
  devise_for :users, path_prefix: 'auth'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  enumerize :profile, in: [:admin, :common], default: :common, predicates: true, scope: true

  scope :active, -> { where(active: true) }

  def active_for_authentication?
    active?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action { @menu = 'users' }
  before_action :set_user, only: [:show, :edit, :update, :destroy, :confirm, :invite]

  # GET /users
  # GET /users.json
  def index
    authorize User

    @users = User.all
    @users = @users.where("name ilike '%' || ? || '%'", params[:name]) if params[:name].present?
    @users = @users.where("email ilike '%' || ? || '%'", params[:email]) if params[:email].present?
    @users = @users.where(profile: params[:profile]) if params[:profile].present?
    @users = @users.where(active: params[:active]) if params[:active].present?
    @users = @users.where('current_sign_in_at >= ?', params[:date_from]) if params[:date_from].present?
    @users = @users.where('current_sign_in_at <= ?', params[:date_to].to_date.end_of_day) if params[:date_to].present?

    @users = @users.reorder(:name => params[:sort_order]) if params[:sort_field] == 'name'
    @users = @users.reorder(:email => params[:sort_order]) if params[:sort_field] == 'email'
    @users = @users.reorder(:profile => params[:sort_order]) if params[:sort_field] == 'profile'
    @users = @users.reorder(:active => params[:sort_order]) if params[:sort_field] == 'active'
    @users = @users.reorder(:current_sign_in_at => params[:sort_order]) if params[:sort_field] == 'date'
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  def invite
    authorize @user
    @user.confirm
    UserMailer.invite(@user).deliver
    redirect_to request.referer, notice: "Email enviado para: #{@user.email}"
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  def confirm
    authorize @user
    @user.confirm
    redirect_to users_path, notice: "E-mail #{@user.email} confirmado."
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # Remove password if it is empty.
    update_params = user_params.dup
    if update_params[:password].empty?
      update_params.delete :password
      update_params.delete :password_confirmation
    end

    respond_to do |format|
      if @user.update(update_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def login_as
    @user = User.find(params[:id])
    authorize @user
    sign_in(@user, bypass: true)
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :profile, :password, :password_confirmation, :status, :client_id, :recipient_id)
    end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Atenção:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <legend>Informações de acesso</legend>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :profile %>

  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :active, collection: [['Ativo', true], ['Inativo', false]], label: 'Situação' %>

  <div class="actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>
    Editar Usuário
  </h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <h2>Usuários</h2>
  <%= link_to '<i class="fa fa-plus"></i> Cadastrar Usuário'.html_safe, new_user_path, :class => 'btn btn-large btn-primary pull-right' %>
</div>

<%= form_with url: {action: action_name}, method: :get, local: true do |f| %>
  <%= hidden_field_tag :sort_field, params[:sort_field] %>
  <%= hidden_field_tag :sort_order, params[:sort_order] %>

  <div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
          <tr>
            <th data-sort-field="name">Nome</th>
            <th data-sort-field="email">E-mail</th>
            <th data-sort-field="active">Situação</th>
            <th data-sort-field="profile">Perfil</th>
            <th data-sort-field="date">Último acesso</th>
            <th width="100px">Opções</th>
          </tr>
          <tr class="filter">
            <th><%= text_field_tag :name, params[:name] %></th>
            <th><%= text_field_tag :email, params[:email] %></th>
            <th><%= select_tag :active, options_for_select([['Ativo', 'true'], ['Inativo', 'false']], params[:active]), prompt: 'Todos' %></th>
            <th><%= select_tag :profile, options_for_select(User.profile.options, params[:profile]), prompt: 'Todos' %></th>
            <th>
              <%= text_field_tag :date_from, params[:date_from], type: 'date', style: 'width: 140px' %>
              <%= text_field_tag :date_to, params[:date_to], type: 'date', style: 'width: 140px; margin-top: 5px;' %>
            </th>
            <th><%= submit_tag "Filtrar" %></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <tr class="odd gradeX">
              <td  style="border-left: 3px solid #eee"><%= link_to user.name, user %></td>
              <td>
                <div><%= user.email %></div>
                <% if user.respond_to? :confirmed? %>
                  <small>
                  <% if user.confirmed? %>
                    <span title="Confirmado em <%= l user.confirmed_at %>">Confirmado</span>
                  <% else %>
                    Não confirmado | <%= link_to 'Confirmar', confirm_user_path(user) %>
                  <% end %>
                  </small>
                <% end %>
              </td>
              <td><%= user.active ? 'Ativo' : 'Inativo' %></td>
              <td><%= user.profile_text %></td>
              <td><%= l user.current_sign_in_at, :format => '%d/%m/%Y %H:%M' if user.current_sign_in_at %></td>
              <td><%= link_to "Editar", edit_user_path(user), class: 'btn btn-default btn-sm' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>
<% end %>

<style>
  tr td, tr th { font-size: 12px; } /* Para não quebrar a tabela na horizontal */
  .filter th { vertical-align: baseline !important; font-size: 12px;}
  th[data-sort-field].active {
    background: #fcfcfc;
  }
  th[data-sort-field] {
    text-decoration: underline;
    cursor: pointer;
  }
  tr input, tr select {
    width: 100%;
    height: 25px;
  }
</style>
<script>
  $(function() {
    var sortBy = $('#sort_field').val();
    if (sortBy)
      $('th[data-sort-field=' + sortBy + ']').addClass('active');

    $('th[data-sort-field]').click(function() {
      var form = $(this).parents('form');
      var field = $(this).data('sort-field');
      var order = $('#sort_order').val() == 'asc' ? 'desc' : 'asc';
      $('#sort_order').val(order);
      $('#sort_field').val(field);
      form.submit();
    });
  });
</script>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>

<div class="panel panel-default">
  <table class="table table-bordered">
    <tr>
      <th>Nome</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th>Perfil</th>
      <td><%= @user.profile_text %></td>
    </tr>
    <tr>
      <th>Situação</th>
      <td><%= @user.active ? 'Ativo' : 'Inativo' %></td>
    </tr>
  </table>

  <div class="panel-footer">
    <%= link_to 'Editar Cadastro', edit_user_path(@user), class: 'btn btn-default' %>
    <%= link_to '<i class="fa fa-trash-o"></i> Deletar'.html_safe, @user, :method => 'delete', 
                 :class => 'btn btn-danger pull-right', :confirm => "Tem certeza que quer deletar esse usuário e todas as suas informações?" %>
  </div>
</div>