config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'samples/:action', controller: 'samples'

  resources :clients
  resources :users do
    get :confirm, on: :member
    get :invite, on: :member
    get :login_as, on: :member
  end
  devise_for :users, path_prefix: 'auth'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true

  has_many :phones, as: :callable, dependent: :delete_all
  accepts_nested_attributes_for :phones, allow_destroy: true

  has_many :emails, as: :emailable, dependent: :delete_all
  accepts_nested_attributes_for :emails, allow_destroy: true

  scope :search,  -> (q) { where("name ilike '%' || ? || '%'", q).by_name }
  scope :by_name, -> { order('name ASC') }
end

app/controllers/clients_controller.rb
class ClientsController < ScaffoldController
  before_action { @menu = 'clients' }

  private
    def collection
      scope = Client.by_name
      if params[:q].present?
        scope = scope.search(params[:q])
      end
      scope
    end

    def permit_params
      [:name, { phones_attributes: [:id, :number, :_destroy],
                emails_attributes: [:id, :address, :_destroy] }]
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= simple_nested_form_for(client, multipart: true) do |f| %>
  <div class="card card-default">
    <div class="card-body">
      <%= show_errors client %>

      <%= f.input :name %>

      <div>
        <%= f.label :phones, 'Telefones' %>
        <div id="phones">
          <%= f.fields_for :phones do |ff| %>
            <div class="row">
              <%= ff.hidden_field :id %>
              <%= ff.input :number, label: false, wrapper_html: { class: 'col-md-2' }, input_html: { class: 'phone' } %>
              <div class="col-md-2">
                <%= ff.link_to_remove 'Remover', class: 'btn btn-default' %>
              </div>
            </div>
          <% end %>
        </div>
        <%= f.link_to_add "Acrescentar Telefone", :phones, :data => {:target => "#phones"}, :class => 'add-nested-field' %>
      </div>

      <hr />

      <div>
        <%= f.label :emails, 'Emails'%>
        <div id="emails">
          <%= f.fields_for :emails do |ff| %>
            <div class="row">
              <%= ff.hidden_field :id %>
              <%= ff.input :address, as: :email, label: false, wrapper_html: { class: 'col-md-4' }, input_html: { class: '' } %>
              <div class="col-md-2">
                <%= ff.link_to_remove 'Remover', class: 'btn btn-default' %>
              </div>
            </div>
          <% end %>
        </div>
        <%= f.link_to_add "Acrescentar Email", :emails, :data => {:target => "#emails"}, :class => 'add-nested-field' %>
      </div>
    </div>

    <div class="card-footer">
      <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
      <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
      <%= link_to "Apagar", @client, 
                  method: :delete, 
                  class: 'btn btn-danger pull-right',
                  data: { confirm: 'Tem certeza que quer apagar?' } if @client.persisted? %> 
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<div class="page-header">
  <h2>Clientes</h2>
  <%= link_to "Novo Cliente", new_client_path, class: 'btn btn-primary' %>
</div>

<div class="card card-default">
  <% if params[:q] %>
    <div class="card-body">
      Resultado da pesquisa por: "<%= params[:q] %>"
    </div>
  <% end %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Telefone</th>
        <th>Email</th>
        <th width="30px"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= link_to client.name, client %></td>
          <td><%= client.phones.map(&:number).join(', ') %></td>
          <td><%= client.emails.map(&:address).join(', ') %></td>
          <td><%= link_to 'Editar', edit_client_path(client), class: 'btn btn-default btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @clients %>
</div>

app/views/clients/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<div class="page-header">
  <h1>
    <%= @client.name %>
  </h1>
  <div class="pull-right">
    <%= link_to "Editar", edit_client_path(@client), class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        Contato
      </div>
      <table class="table">
        <tr>
          <td><i class="fa fa-envelope"></i></td>
          <td><%= @client.emails.map {|a| link_to a.address, "mailto:#{a.address}" }.join(', ').html_safe %></td>
        </tr>
        <tr>
          <td><i class="fa fa-phone"></i></td>
          <td><%= @client.phones.map {|a| link_to a.number, "tel:#{a.number}" }.join(', ').html_safe %></td>
        </tr>
      </table>
    </div>
  </div>
</div>